# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

services:
  lando-ui:
    build:
      context: ../lando-ui/
      dockerfile: ./docker/Dockerfile-dev
    image: suite_lando-ui
    volumes:
      - ../lando-ui:/app
    environment:
      - LOG_LEVEL=DEBUG
      - WERKZEUG_DEBUG_PIN=132435
    tty: true
    stdin_open: true
  lando-ui.test:
    volumes:
      - ../lando-ui:/app
