# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

services:
  phabricator:
    platform: linux/x86_64
    build:
      context: ../phabricator/
      dockerfile: ./Dockerfile
      target: development
    image: suite_phabricator
    volumes:
      - phabricator-src-local:/app/phabricator/src
      - phabricator-moz-extensions-local:/app/moz-extensions
  phabricator.test:
    platform: linux/x86_64
    volumes:
      - phabricator-src-local:/app/moz-extensions
      - phabricator-moz-extensions-local:/app/phabricator/src

volumes:
  phabricator-src-local:
    driver: local
    driver_opts:
      type: none
      device: '$PWD/../phabricator/src'
      o: bind
  phabricator-moz-extensions-local:
    driver: local
    driver_opts:
      type: none
      device: '$PWD/../phabricator/moz-extensions'
      o: bind
