# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: '3.4'
services:
  lando-api:
    build:
      context: ../lando-api/
      # Use ./Dockerfile-dev to run using flask's built-in dev server
      # Use ./Dockerfile to run using uwsgi, similar to remote environments
      dockerfile: ./Dockerfile-dev
    image: suite_lando-api
    environment:
      PORT: 9000
      VERSION_PATH: /config/version.json
    volumes:
      - ../lando-api:/app
      - ../lando-api/docker/dev-version.json:/version.json
      - ../lando-api/migrations:/migrations
      - patches:/patches

  lando-api.landing-worker:
    build:
      context: ../lando-api/
      # Use ./Dockerfile-dev to run using flask's built-in dev server
      # Use ./Dockerfile to run using uwsgi, similar to remote environments
      dockerfile: ./Dockerfile-dev
    image: suite_lando-api
    command: ["start-landing-worker"]
    environment:
      ENV: localdev
      # TREESTATUS_URL: "http://autoland.treestatus:8000/"
      DATABASE_URL: postgresql://postgres:password@lando-api.db/postgres
      PHABRICATOR_URL: http://phabricator.test/
      PHABRICATOR_UNPRIVILEGED_API_KEY: api-lefsv24henzsbzpw337bhizawuyh
      PHABRICATOR_ADMIN_API_KEY: api-lefsv24henzsbzpw337bhizawuyh
      SENTRY_DSN:
      CELERY_BROKER_URL: redis://redis.queue/0
      OIDC_IDENTIFIER: https://lando-api.test
      LANDO_UI_URL: https://lando.test
      REPO_CLONES_PATH: /repos
      REPOS_TO_LAND: first-repo,second-repo,third-repo
      DEFAULT_GRACE_SECONDS: 10
      LANDING_WORKER_USERNAME: app
      LANDING_WORKER_TARGET_SSH_PORT: 8022
      SSH_PRIVATE_KEY: |
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEIMiMNKEkf0vr4HrhUIrq0e9NjGNPArN7L1uy/HQZ1dA8oAoGCCqGSM49
        AwEHoUQDQgAEdakNgjerNLFXy1uMfwLjPd5/pBTbIEoZMdMV/o6s+uoMg776LF+v
        gtbfIaZbhDcJElzHwpnqGfHYU+cM4KyurA==
        -----END EC PRIVATE KEY-----
    user: root
    volumes:
      - ../lando-api:/app
      - ../lando-api/migrations:/migrations
      # Prevent writing python cache to the host.
      - caches_cache:/app/.cache/
      - /repos
      - patches:/patches
    depends_on:
      - lando-api.db
      - redis.queue

  lando-api.revision-worker:
    build:
      context: ../lando-api/
      dockerfile: ./Dockerfile-dev
    image: suite_lando-api
    command: ["start-revision-worker"]
    environment:
      ENV: localdev
      DATABASE_URL: postgresql://postgres:password@lando-api.db/postgres
      PHABRICATOR_URL: http://phabricator.test/
      PHABRICATOR_UNPRIVILEGED_API_KEY: api-lefsv24henzsbzpw337bhizawuyh
      PHABRICATOR_ADMIN_API_KEY: api-lefsv24henzsbzpw337bhizawuyh
      SENTRY_DSN:
      CELERY_BROKER_URL: redis://redis.queue/0
      OIDC_IDENTIFIER: https://lando-api.test
      LANDO_UI_URL: https://lando.test
      REPO_CLONES_PATH: /repos
      REPOS_TO_LAND: first-repo,second-repo,third-repo
    user: root
    volumes:
      - ../lando-api:/app
      - ../lando-api/migrations:/migrations
      # Prevent writing python cache to the host.
      - caches_cache:/app/.cache/
      - /repos
      - patches:/patches
    depends_on:
      - lando-api.db
      - redis.queue

  redis.queue:
    image: redis:3.2-alpine

  lando-ui.test:
    volumes:
      - ../lando-api:/app
      - ../lando-api/docker/dev-version.json:/version.json
      - ../lando-api/migrations:/migrations

volumes:
    caches_cache:
    patches:
