services:
  git_hg_sync-cinnabar_init:
    platform: linux/x86_64
    user: 101:101 # match the owner in the Cgit container
    image: mozilla/git_hg_sync # we need git-cinnabar to set-up the clones
    build:
      context: ../git-hg-sync
    volumes:
      - ./docker/git-hg-sync/scripts:/scripts:ro
      - git-repos:/opt/git
      - cgit-cache:/opt/cgit/cache # we need access to this so we can clear the cache
    entrypoint: ["/scripts/cinnabar-init.sh"]
    depends_on:
      autoland.hg.test:
        condition: service_healthy
      git.test:
        condition: service_healthy

  git_hg_sync:
    platform: linux/x86_64
    image: mozilla/git_hg_sync
    build:
      context: ../git-hg-sync
    command: --config /app/config-suite.toml --log-raw-level debug
    volumes:
      - ../git-hg-sync:/app:z
      - ./docker/git-hg-sync/config-suite.toml:/app/config-suite.toml
      - git_hg_sync_clones:/clones
    environment: &pulse_env
      PULSE_HOST: pulse.test
      PULSE_PORT: 5672
      PULSE_QUEUE: queue/suite/git-hg-sync
      PULSE_EXCHANGE: exchange/suite/git-hg-sync
      PULSE_ROUTING_KEY: git-hg-sync
      PULSE_SSL: "" # False
      # Same as the lando.hg-landing_worker
      SSH_PRIVATE_KEY: |
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEIMiMNKEkf0vr4HrhUIrq0e9NjGNPArN7L1uy/HQZ1dA8oAoGCCqGSM49
        AwEHoUQDQgAEdakNgjerNLFXy1uMfwLjPd5/pBTbIEoZMdMV/o6s+uoMg776LF+v
        gtbfIaZbhDcJElzHwpnqGfHYU+cM4KyurA==
        -----END EC PRIVATE KEY-----
    depends_on:
      git_hg_sync-cinnabar_init:
        condition: service_completed_successfully
      pulse.test:
        condition: service_healthy

  lando:
    depends_on:
      git_hg_sync-cinnabar_init:
        condition: service_completed_successfully

  lando.git-landing-worker:
    environment:
      <<: *pulse_env

volumes:
  git_hg_sync_clones:
