# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

services:
  lando:
    build:
      context: ../lando/.
    image: suite_lando
    stdin_open: true
    tty: true
    command: bash -c "
      lando generate_version_file &&
      lando collectstatic --clear --no-input &&
      lando setup_dev &&
      lando runserver 0.0.0.0:80"
    user: "${UID}:${GID}"  # needed for file generation in the mounted volumes
    volumes:
      - ../lando:/code
      - ../lando/staticfiles:/staticfiles
      - ../lando-prorotype/media:/mediafiles

  lando.hg-landing-worker: &landing_worker
    image: suite_lando
    user: "${UID}:${GID}"  # needed for file generation in the mounted volumes
    volumes:
      - ../lando:/code
      - ../lando/staticfiles:/staticfiles
      - ../lando-prorotype/media:/mediafiles

  lando.test:
    build: ../lando/nginx
    depends_on:
      - lando
    volumes:
      - ../lando/staticfiles:/staticfiles
      - ../lando/media:/mediafiles

  lando.git-landing-worker:
    <<: *landing_worker

  lando.db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 1s
      timeout: 1s
      retries: 10

  lando.redis:
    image: redis:7.2
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  lando.celery:
    image: suite_lando
    command: lando start_celery_worker
    depends_on:
      lando.redis:
        condition: service_healthy

volumes:
  media:
