#!/bin/sh
# A simple wrapper that takes care of using compose overrides if present.

if [ -e docker-compose.override.yml ]; then
  set - -f docker-compose.override.yml "${@}"
fi
set - compose -f docker-compose.yml "${@}"

docker "${@}"
